# GET http://127.0.0.1:9080 HTTP/1.1

# GET http://127.0.0.1:9080/api/data HTTP/1.

POST  http://127.0.0.1:9080/api/data HTTP/1.1
Content-Type: application/json

{"name": "Charlie", "age": 28, "city": "Tokyo"}